### ISSUE TITLE
Error/raise points to wrong function

### ISSUE THREAD

**Issue by FinlayDaG33k** [FinlayDaG33k/deno-lib#11]
With the massive changes coming in #7, we've added a `raise` function to more easily allow us to raise errors through null-coalescing, as this is not natively supported by TypeScript at the moment.  

However, this issue causes stacktraces to point to the `raise` function itself rather than the place where `raise` was called:

```ts
const whatever = blablabla.bla ?? raise('Test', BlahError);
```

```
error: Uncaught BlahError: Test
    const e = new Error(err);
              ^
    at raise (file:///F:/repos/FinlayDaG33k/chomp/error/raise.ts:14:15)
    at file:///F:/repos/FinlayDaG33k/chomp/error/raise.ts:23:1
```

This should be fixed so that stacktraces allow people to more easily find where something goes wrong.  
I think `Error.captureStackTrace` might help for a solution but I'm currently unsure.

**Comment by FinlayDaG33k** [comment]
Accidentally clicked the wrong button, whoops.
